// Mocks generated by Mockito 5.4.6 from annotations
// in zentriq/test/viewmodels/ecosystem_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:zentriq/core/utils/result.dart' as _i4;
import 'package:zentriq/domain/entities/project.dart' as _i5;
import 'package:zentriq/domain/repositories/project_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i2.ProjectRepository {
  MockProjectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> getAllProjects() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProjects, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#getAllProjects, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> getProjectsByCategory(
    _i5.ProjectCategory? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectsByCategory, [category]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#getProjectsByCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> getFeaturedProjects({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeaturedProjects, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#getFeaturedProjects, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> getRecentlyLaunchedProjects({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentlyLaunchedProjects, [], {
              #limit: limit,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#getRecentlyLaunchedProjects, [], {
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> getPopularProjects({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularProjects, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#getPopularProjects, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<_i5.Project>> getProjectById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Project>>.value(
              _i6.dummyValue<_i4.Result<_i5.Project>>(
                this,
                Invocation.method(#getProjectById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Project>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> searchProjects(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchProjects, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#searchProjects, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Project>>> refreshProjects() =>
      (super.noSuchMethod(
            Invocation.method(#refreshProjects, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Project>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Project>>>(
                this,
                Invocation.method(#refreshProjects, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Project>>>);
}
