// Mocks generated by Mockito 5.4.6 from annotations
// in zentriq/test/viewmodels/news_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:zentriq/core/utils/result.dart' as _i4;
import 'package:zentriq/domain/entities/news_article.dart' as _i5;
import 'package:zentriq/domain/repositories/news_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepository extends _i1.Mock implements _i2.NewsRepository {
  MockNewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getAllNews() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNews, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#getAllNews, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getLatestNews({
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestNews, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#getLatestNews, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getTrendingNews({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingNews, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#getTrendingNews, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getNewsByCategory(
    _i5.NewsCategory? category, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNewsByCategory, [category], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(
                  #getNewsByCategory,
                  [category],
                  {#limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getBreakingNews({
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBreakingNews, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#getBreakingNews, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<_i5.NewsArticle>> getNewsById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNewsById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.NewsArticle>>.value(
              _i6.dummyValue<_i4.Result<_i5.NewsArticle>>(
                this,
                Invocation.method(#getNewsById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.NewsArticle>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> searchNews(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNews, [query], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#searchNews, [query], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> getBookmarkedNews() =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedNews, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#getBookmarkedNews, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);

  @override
  _i3.Future<_i4.Result<void>> bookmarkNews(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#bookmarkNews, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#bookmarkNews, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeBookmark(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeBookmark, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeBookmark, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> markAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#markAsRead, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.NewsArticle>>> refreshNews() =>
      (super.noSuchMethod(
            Invocation.method(#refreshNews, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.NewsArticle>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.NewsArticle>>>(
                this,
                Invocation.method(#refreshNews, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.NewsArticle>>>);
}
